import { z } from "zod";

export const movementSchema = z.object({
    id: z.number(),
    quantity: z.number(),
    comment: z.string(),
    createdAt: z.string(),
    movementType: z.enum([
        "MOVEMENT_STOCK_RECEIVE",
        "MOVEMENT_STOCK_INCREASE",
        "MOVEMENT_STOCK_DECREASE",
        "MOVEMENT_STOCK_RECOVERY",
        "MOVEMENT_STOCK_TRANSFER",
        "MOVEMENT_STOCK_REFUND",
        "MOVEMENT_LINE_ALLOCATE",
        "MOVEMENT_LINE_ALTER",
        "MOVEMENT_LINE_RETURN",
        "MOVEMENT_LINE_CHANGE",
        "MOVEMENT_LINE_CANCELED",
        "MOVEMENT_LINE_LOST",
        "MOVEMENT_LINE_MISSING",
        "MOVEMENT_LINE_DELIVERED",
        "MOVEMENT_LINE_SIMULTANEOUS",
    ]),
    userName: z.string(),
    modelId: z.number(),
    modelName: z.string(),
    movements_StockLots: z.array(z.number()),
    stockLotReceiverId: z.number(),
    stockLotReceiverBatch: z.string(),
    stockLotEmitterId: z.number(),
    stockLotEmitterBatch: z.string(),
    deliveryLineId: z.number(),
});
